### ISSUE TITLE
Generate reports from AnnData (for conversions where CAS content remains in header)

### ISSUE THREAD

**Issue by dosumis** [cellannotation/cas-tools#11]
Reports = dataframes following table structure in TDT.
Options for annotation reports:
 1. All Annotations
 2. Annotation specified by a list of key(labelset), value(cell_label) pairs

**Comment by dosumis** [comment]
Initial implementation here: https://github.com/cellannotation/cas-tools/blob/main/notebooks/test_reports.ipynb

BUT - this is not set to work from CAS embedded in anndata - it should be 
A bug in implementation expects cell_ids in schema:

```python
import json
import anndata as ad
fu = ad.read_h5ad('/Volumes/Extreme SSD/tdt_datasets/Siletti/Siletti_all_non_neuronal_cells_merged.h5ad')
Siletti_cas = json.loads(fu.uns['cas'])
get_all_annotations(Siletti_cas)
Traceback (most recent call last):
  File "/Users/do12/Documents/GitHub/cas-tools/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-d58917bf63cf>", line 1, in <module>
    get_all_annotations(Siletti_cas)
  File "/Users/do12/Documents/GitHub/cas-tools/src/cas/reports.py", line 17, in get_all_annotations
    df = df.drop('cell_ids', axis=1)
  File "/Users/do12/Documents/GitHub/cas-tools/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
  File "/Users/do12/Documents/GitHub/cas-tools/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/Users/do12/Documents/GitHub/cas-tools/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/do12/Documents/GitHub/cas-tools/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['cell_ids'] not found in axis"
```

See https://github.com/cellannotation/cas-tools/blob/1bc5127ca81a94922d3319805ada12ea2c867440/src/cas/reports.py#L17

**Comment by hkir-dev** [comment]
bug fix implemented https://github.com/cellannotation/cas-tools/commit/486d3333f9f31f2aac6c833049523b1dff504609
